docs: polish wording in NatSpec
sablier-labs/v2-core pull request #1014
Opened 2024-08-13 08:29 UTC by PaulRBerg

2024-08-13 10:26 UTC, smol-ninja requested changes
I like the polished version.

2024-08-13 10:26 UTC, smol-ninja commented on src/core/types/DataTypes.sol
> +    /// @notice Struct encapsulating the parameters of the {SablierV2LockupDynamic.createWithDurations} function.
should be `SablierLockupDynamic`.

2024-08-13 10:26 UTC, smol-ninja commented on src/core/types/DataTypes.sol
> +    /// @notice Struct encapsulating the parameters of the {SablierV2LockupDynamic.createWithTimestamps} function.
should be `SablierLockupDynamic`.

2024-08-13 10:26 UTC, smol-ninja commented on src/core/types/DataTypes.sol
> +    /// @notice Segment struct used at runtime in {SablierV2LockupDynamic.createWithDurations}.
should be `SablierLockupDynamic`.

2024-08-13 10:50 UTC, PaulRBerg commented
Thanks for the review. Fixed the issues.

2024-08-14 12:48 UTC, andreivladbrg commented
Will merge it first, since it is a small PR and it causes no conflicts in the claim dry fy.

2024-08-14 12:49 UTC, merged