refactor: use "given" keyword in branching trees
sablier-labs/v2-core pull request #656
Opened 2023-08-21 10:01 UTC by PaulRBerg

Merges the work done by @smol-ninja onto `main` and closes https://github.com/sablier-labs/v2-core/issues/621.

Refs:

- https://github.com/sablier-labs/v2-core/pull/641
- https://github.com/sablier-labs/v2-core/pull/642

2023-08-21 10:28 UTC, PaulRBerg commented
@andreivladbrg if you could have a quick look that would be helpful.

2023-08-22 08:03 UTC, andreivladbrg requested changes
Missed tree:  

https://github.com/sablier-labs/v2-core/blob/test/improve-tree-wording/test/integration/concrete/lockup/cancel-multiple/cancelMultiple.tree

Should we use here "given?

https://github.com/sablier-labs/v2-core/blob/aedff61e39fa0652d314dda43b498a0b4488c8a2/test/integration/concrete/lockup/cancel/cancel.tree#L37

https://github.com/sablier-labs/v2-core/blob/aedff61e39fa0652d314dda43b498a0b4488c8a2/test/integration/concrete/lockup/cancel/cancel.tree#L64

https://github.com/sablier-labs/v2-core/blob/aedff61e39fa0652d314dda43b498a0b4488c8a2/test/integration/concrete/lockup/cancel/cancel.tree#L68

2023-08-22 08:26 UTC, PaulRBerg commented on test/integration/concrete/lockup/cancel/cancel.tree
>                    │  ├── when the recipient is not a contract
The recipient is a user-provided parameter, so I would stick with "when" for it.

This is similar to how we use "when" for ERC-20 compliant contracts in the create function trees.

2023-08-22 08:27 UTC, PaulRBerg commented on test/integration/concrete/nft-descriptor/map-symbol/mapSymbol.tree
> +    ├── when the NFT contract is LockupDynamic
Whether the NFT contract is unknown or known is a background property (it's part of the implementation of the contract-under-test).

But the NFT contract address is a separate matter, and its address is a user-provided parameter.

2023-08-22 08:27 UTC, PaulRBerg commented on test/integration/concrete/nft-descriptor/safe-asset-symbol/safeAssetSymbol.tree
> +├── when not an ERC-20 contract
No. This is a user-provided parameter.

2023-08-22 08:28 UTC, PaulRBerg commented on test/integration/concrete/lockup/withdraw/withdraw.tree
>                                 ├── when the recipient is not a contract
"when" is fine because this is a user-provided parameter.

2023-08-22 08:28 UTC, PaulRBerg commented on test/integration/concrete/lockup-dynamic/streamed-amount-of/streamedAmountOf.tree
>  streamedAmountOf.t.sol
yep, good catch

2023-08-23 08:45 UTC, PaulRBerg commented
@andreivladbrg, can you approve the PR?

2023-08-23 15:06 UTC, andreivladbrg approved these changes

2023-08-23 17:29 UTC, merged