docs: guideline for fork testing
sablier-labs/v2-core pull request #740
Opened 2023-12-09 02:40 UTC by smol-ninja

fixes #715

2023-12-09 06:04 UTC, PaulRBerg requested changes
Thanks @smol-ninja, generally LGTM

2023-12-09 06:04 UTC, PaulRBerg commented on CONTRIBUTING.md
> +### Local setup
Let's make this the first section.

2023-12-09 06:04 UTC, PaulRBerg commented on CONTRIBUTING.md
> +[github secret](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions):
Let's say "in your GitHub Secrets".

2023-12-09 06:04 UTC, PaulRBerg commented on CONTRIBUTING.md
> +- RPC_URL_MAINNET
Let's order this list alphabetically

2023-12-09 06:05 UTC, PaulRBerg commented
Btw I suppose that you created this PR from your personal fork to test the environment variables, but for future PRs, you should be able to create branches directly in the canonical V2 Core repo.

2023-12-09 12:52 UTC, smol-ninja commented
> Btw I suppose that you created this PR from your personal fork to test the environment variables, but for future PRs, you should be able to create branches directly in the canonical V2 Core repo.

Yes, you got it. But the issue is not yet resolved. The fork tests will fail on a PR requested by an external contributor despite them passing in the local repo.

Secrets are not passed from the source branch to the workflows during a PR raised by an external contributor.

Ref: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository

There is a solution: by using `pull_request_target` instead of `pull_request` event in GitHub Actions, the workflow will operate within the context of the contributor's forked repository secrets each time they open a new pull request.

Ref:
- https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks
- https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

Risks involved:
We just have to be extra careful when using `pull_request_target` as mentioned in this [Github blog](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/#:%7E:text=of%20the%20PR.-,Having%20said%20that,-%2C%20mixing%20pull_request_target%20with).

Should I create another issue to look at it in the future if its not a priority? I can also go ahead and do some local testing in my repo to see how `pull_request_target` event works.

2023-12-11 10:45 UTC, smol-ninja commented
@PaulRBerg should I merge it?

2023-12-11 10:58 UTC, PaulRBerg commented
Apologies @smol-ninja, it's a busy day on the business front. I will review this PR later, if that's ok.

2023-12-15 13:28 UTC, PaulRBerg commented
> the issue is not yet resolved. The fork tests will fail on a PR requested by an external contributor despite them passing in the local repo.

I see!

> Should I create another issue to look at it in the future if its not a priority?

Yes, please.

> should I merge it?

Merged now. Thank you for your contribution.

2023-12-15 13:29 UTC, merged