Polish deploy-multi-chain script
sablier-labs/v2-core pull request #744
Opened 2023-12-13 21:50 UTC by smol-ninja

fixes https://github.com/sablier-labs/v2-core/issues/743

2023-12-13 21:52 UTC, smol-ninja commented
@andreivladbrg let me know if looks good.

2023-12-14 11:30 UTC, andreivladbrg commented
>I had to change MAINNET_RPC_URL with RPC_URL_MAINNET in foundry.toml because fork test was failing as we use RPC_URL_MAINNET in github secret.

github secrets can be updated as well, my intention is to switch from RPC_URL_{CHAIN_NAME} to {CHAIN_NAME}_RPC_URL because it is easier to group them and to alphabetically order in `.env`.

2023-12-14 11:54 UTC, smol-ninja commented
Agree. I've changed it back https://github.com/sablier-labs/v2-core/pull/744/commits/083d6d7b4b395fa2f40920fbf59d1cd8b6d6bc06

2023-12-14 12:18 UTC, andreivladbrg requested changes
I've added the comptrollers here with the intention of adding a deploy core 3 script that does not deploy the comptroller. Can you also verify if there have been any changes between `release` and `staging` in `src/SablierV2Comptroller` or `src/interfaces/ISablierV2Comptroller`?

2023-12-14 12:18 UTC, andreivladbrg commented on shell/deploy-multi-chains.sh
> +    echo -e "${EC}Error:\nThis script requires Bash version 4.0.0 or higher.\nYou are currently using Bash version ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}.${BASH_VERSINFO[2]}.\nPlease upgrade your Ba
readability can be increased

2023-12-14 12:20 UTC, andreivladbrg commented
pushed two commits, lmk if it looks good now

2023-12-14 12:56 UTC, smol-ninja commented
LGTM!

2023-12-14 13:01 UTC, merged