refactor: consistency in calldata related struct parameters
sablier-labs/v2-core pull request #784
Opened 2024-01-06 15:44 UTC by smol-ninja

Closes #728.

2024-01-06 20:39 UTC, andreivladbrg requested changes
i think you've missed the best practice for how we pass arguments when calling a function with a struct as a param

thus, only the order from `src/types/DataTypes.sol` should have been changed

2024-01-06 20:39 UTC, andreivladbrg commented on src/SablierV2LockupDynamic.sol
> +                sender: params.sender,
the order here should have remained the same, it was alphabetically ordered

2024-01-06 20:39 UTC, andreivladbrg commented on src/SablierV2LockupLinear.sol
> +                totalAmount: params.totalAmount,
the order here should have remained the same, it was alphabetically ordered

2024-01-06 20:39 UTC, andreivladbrg commented on test/fork/LockupDynamic.t.sol
> +                broker: params.broker
it was alphabetically ordered

2024-01-06 20:39 UTC, andreivladbrg commented on test/fork/LockupLinear.t.sol
> +                broker: params.broker
it was alphabetically ordered

2024-01-06 20:39 UTC, andreivladbrg commented on test/integration/fuzz/lockup-linear/createWithRange.t.sol
> +                broker: params.broker
it was alphabetically ordered

2024-01-06 20:39 UTC, andreivladbrg commented on test/utils/Defaults.sol
> +            broker: broker()
it was alphabetically ordered

2024-01-06 20:39 UTC, andreivladbrg commented on test/utils/Defaults.sol
> +            broker: broker()
it was alphabetically ordered

2024-01-07 07:04 UTC, smol-ninja commented
Thanks, @andreivladbrg for the feedback. Please find my comments below.

> I think you've missed the best practice for how we pass arguments when calling a function with a struct as a param

I was aware that we generally follow an alphabetically ordered pattern. So I looked at the [Sablier guidelines](https://sablier.notion.site/Sablier-Coding-Practices-Contracts-2f5920cf497646b4a2ea982c1bacb5a8) before making these changes. However, in the original code, it does not appear to be alphabetically ordered (please see below and correct me if I misunderstood it - a b c t r s s s t).

```solidity
 streamId = _createWithMilestones(
            LockupDynamic.CreateWithMilestones({
                asset: params.asset,
                broker: params.broker,
                cancelable: params.cancelable,
                transferable: params.transferable,
                recipient: params.recipient,
                segments: segments,
                sender: params.sender,
                startTime: uint40(block.timestamp),
                totalAmount: params.totalAmount
            })
        );
```

Now my rationale behind making these changes was **code consistency**. By following the same order, as declaring structs in the `DataTypes.sol`, throughout the codebase, it appears to make code easier to understand at a glance and reduce the likelihood of missing out on any struct variable since they are now in the same order.

However, I acknowledge your point that we should adhere to best practices for function parameters. If the alphabetical ordering of the arguments is a standard that we want to maintain, I am willing to revert the changes and keep it alphabetically ordered in the function.

2024-01-07 12:08 UTC, andreivladbrg commented
Thanks @smol-ninja for your detailed response

> in the original code, it does not appear to be alphabetically ordered

indeed, it was not alphabetically ordered, it was a mistake on our end, `transferable` should have been the last one

> Now my rationale behind making these changes was code consistency. By following the same order, as declaring structs in the DataTypes.sol, throughout the codebase, it appears to make code easier to understand at a glance and reduce the likelihood of missing out on any struct variable since they are now in the same order.

i see, i understand your rationale, and tbh, i'm starting to like it and am leaning towards it as being the better choice. @PaulRBerg i'm curious about your opinion on this

2024-01-11 13:46 UTC, smol-ninja commented
@PaulRBerg we'd love your opinion on this.

2024-01-12 11:25 UTC, PaulRBerg commented
This is an exemplary case of **conflicting heuristics** (which are inevitable in life).

- On the one hand, we want to order the struct fields in a non-alphabetic way to optimize the gas consumption.
- On the other hand, we want to order the inputs alphabetically in the tests (to adhere to our best practice).

So the dilemma is: should we not apply the alphabetical order heuristic in this case (the tests)?

While I can't think of any decisive argument, I'm slightly more inclined to go with the non-alphabetic approach (the one that @smol-ninja wishes to implement). The reason for this is that it would (ironically) create more consistency among our create function calls - across the production code in `src`, the test code in `test`, and our [examples](https://github.com/sablier-labs/examples).

2024-01-12 11:56 UTC, andreivladbrg commented
> I'm slightly more inclined to go with the non-alphabetic approach (the one that @smol-ninja wishes to implement). The reason for this is that it would (ironically) create more consistency among our create function calls - across the production code in src, the test code in test, and our [examples](https://github.com/sablier-labs/examples).

yeah, completely relatable

2024-01-12 12:34 UTC, smol-ninja commented
> On the one hand, we want to order the struct fields in a non-alphabetic way to optimize the gas consumption

As discussed [here](https://github.com/sablier-labs/v2-core/issues/728#issuecomment-1877065940), the order of parameters does not affect gas usage in this case.

However, even then, I completely agree that it creates more consistency. Since, we all agree on this, I will merge this PR.

2024-01-12 12:53 UTC, merged