feat: declare maxCount in BaseScript
sablier-labs/v2-core pull request #825
Opened 2024-02-16 14:57 UTC by andreivladbrg

I have named it `maxCount` because it is going to be used for both segments and tranches.

2024-02-16 17:47 UTC, smol-ninja requested changes
LGTM.

2024-02-16 17:47 UTC, smol-ninja commented on script/Base.s.sol
> +    uint256 internal maxCount;
should be above `mnemonic` (alphabetically)

2024-02-16 18:35 UTC, PaulRBerg requested changes
feedback below

2024-02-16 18:35 UTC, PaulRBerg commented on script/Base.s.sol
> +    /// transactions stay within the block gas limit.
Let's change to:

> The upper limit on the length of data structures to ensure that transactions stay within the block gas limit

2024-02-16 18:35 UTC, PaulRBerg commented on script/Base.s.sol
> +        // Sets `maxCount` to 300 for Avalanche, or 500 for all other chains.
`and` instead of `or`.

2024-02-17 12:45 UTC, andreivladbrg commented
addressed your suggestions, does it look good now?

2024-02-17 14:42 UTC, smol-ninja approved these changes

2024-02-17 14:44 UTC, merged