perf: emit events before hook calls
sablier-labs/v2-core pull request #940
Opened 2024-06-07 12:28 UTC by smol-ninja

Closes https://github.com/sablier-labs/v2-core/issues/939.

2024-06-07 12:44 UTC, andreivladbrg commented
@smol-ninja let's not udpate yet the precompiles, will do it after we address all the findings

2024-06-07 13:51 UTC, andreivladbrg requested changes
Since the only place where the `updateMetadata` modifier is used is in the `_update` hook, why not remove it completely and emit the event individually in the function? This approach is also more gas efficient

2024-06-07 14:16 UTC, smol-ninja commented
Agree. Changing it right away.

2024-06-07 16:16 UTC, smol-ninja commented
All changes done. You can review it now @andreivladbrg.

2024-06-07 19:56 UTC, PaulRBerg commented on src/abstracts/SablierV2Lockup.sol
> +        // Emits an ERC-4906 event to trigger an update of the NFT metadata.
Let's say just `Emit` here.

2024-06-07 19:56 UTC, PaulRBerg approved these changes
just one comment, otherwise LGTM

2024-06-09 14:43 UTC, smol-ninja commented
@andreivladbrg looks good to merge?

2024-06-10 11:06 UTC, andreivladbrg approved these changes
yes ser

<img width="581" alt="image" src="https://github.com/sablier-labs/v2-core/assets/99738872/5cfef971-cc7c-4e21-8fad-8308784cd123">

2024-06-10 11:07 UTC, merged