[Implement] issues #900 - Rename ASSET to FORK_ASSET in Fork.t.sol
sablier-labs/v2-core pull request #969
Opened 2024-07-08 16:12 UTC by EbiPenMan

The following name changes were made:
- Rename ASSET to FORK_ASSET
- Rename HOLDER to FORK_ASSET_HOLDER

And all the tests passed:
![image](https://github.com/sablier-labs/v2-core/assets/7556608/d95aa826-5b1c-428a-b188-bde1a6865a64)

2024-07-08 17:15 UTC, chista0x commented
@smol-ninja Can you explain me about test automation and the error it gives? I don't know exactly what the error is about?

Does every pool request have to pass all automated tests?

2024-07-08 17:47 UTC, chista0x commented
Yes, it is true that the problem is the length of the line.
![image](https://github.com/sablier-labs/v2-core/assets/151044987/5aca7472-4aca-4d25-bb6f-8287430cc9d9)

Do you use `forge fmt` to format the code? Because in the tests, the format of the code is checked with this accuracy.
![image](https://github.com/sablier-labs/v2-core/assets/151044987/79cb4797-07f9-4555-8337-28998dbd5123)

 If so, I will apply it in the next merge request. But by applying formatting through `forge fmt`, other codes are arranged. Do you want me to do it?

2024-07-08 17:50 UTC, EbiPenMan commented
Yes, it is true that the problem is the length of the line.
![image](https://github.com/sablier-labs/v2-core/assets/151044987/5aca7472-4aca-4d25-bb6f-8287430cc9d9)

Do you use `forge fmt` to format the code? Because in the tests, the format of the code is checked with this accuracy.
![image](https://github.com/sablier-labs/v2-core/assets/151044987/79cb4797-07f9-4555-8337-28998dbd5123)

 If so, I will apply it in the next merge request. But by applying formatting through `forge fmt`, other codes are arranged. Do you want me to do it?

2024-07-08 18:52 UTC, PaulRBerg commented
Thank you for your PR, @EbiPenMan!

> But by applying formatting through `forge fmt`, other codes are arranged. Do you want me to do it?

Yes, `forge fmt` is what solves the linting issues.

As a side note - we recommend using VSCode when making contributions to this repository. See the [Contributor's guide](https://github.com/sablier-labs/v2-core/blob/main/CONTRIBUTING.md).

2024-07-08 19:33 UTC, EbiPenMan commented
> Thank you for your PR, @EbiPenMan!
You're welcome.

I am very interested in participating in blockchain projects, especially in solidity, foundry, and rust, to learn something and help.
Of course, I didn't do anything special about this issue, but it was a good start.

I could not find a bug in your contest, but at least I helped here. :D

2024-07-08 22:37 UTC, smol-ninja requested changes
Thank you very much @EbiPenMan for making the changes. The PR is now passing the lint test which is great 💪.

I have left some comments below which you may address if you like. Also, it seems like the fork test is failing. Its probably because you may not have added `RPC_URL_MAINNET` variable in your repo, as mentioned in the [contributing guidelines](https://github.com/sablier-labs/v2-core/blob/main/CONTRIBUTING.md#pull-requests) - pt 01. If you do so, it should pass fork test as well. Even if you have added and its failing, please let me know.

2024-07-08 22:37 UTC, smol-ninja commented on test/fork/Fork.t.sol
> +        // Make the FORK_ASSET_HOLDER the caller in this test suite.
```suggestion
        // Make the forked asset holder the caller in this test suite.
```

2024-07-08 22:37 UTC, smol-ninja commented on test/fork/Fork.t.sol
> +        // Query the initial balance of the FORK_ASSET_HOLDER.
```suggestion
        // Query the initial balance of the forked asset holder.
```

2024-07-08 22:37 UTC, smol-ninja commented on test/fork/Fork.t.sol
> +        // The goal is to not have overlapping users because the FORK_ASSET balance tests would fail otherwise.
```suggestion
        // The goal is to not have overlapping users because the forked asset balance tests would fail otherwise.
```

2024-07-08 22:37 UTC, smol-ninja commented on test/fork/LockupDynamic.t.sol
> +        // Make the FORK_ASSET_HOLDER the caller.
```suggestion
        // Make the holder the caller.
```

2024-07-08 22:37 UTC, smol-ninja commented on test/fork/LockupLinear.t.sol
> +        // Make the FORK_ASSET_HOLDER the caller.
```suggestion
        // Make the holder the caller.
```

2024-07-08 22:37 UTC, smol-ninja commented on test/fork/LockupTranched.t.sol
> +        // Make the FORK_ASSET_HOLDER the caller.
```suggestion
        // Make the holder the caller.
```

2024-07-09 06:43 UTC, EbiPenMan commented
@smol-ninja  thanks for your help. Yes, you are right, the problem was the missing environment variable. I added them and tested the workflow myself and all the steps passed.

https://github.com/EbiPenMan/sablier-labs-v2-core/actions/runs/9851734720

2024-07-09 17:42 UTC, smol-ninja approved these changes
LGTM now. Thank you for making the changes. Don't mind the failing fork tests. Github doesn't load the environment variables from the external repo due to security reasons. I will let @andreivladbrg have a second look now before merging it.

2024-07-19 10:25 UTC, smol-ninja commented
Thanks @andreivladbrg for the review and @EbiPenMan for creating this PR. I am going to merge it now.

2024-07-19 10:25 UTC, merged